### ISSUE TITLE
Elasticsearch: Set doc_id based on a specific ES document field

### ISSUE THREAD

**Issue by jan-tosovsky-cz** [emptycrown/llama-hub#114]
It would be handy to have the ability to map doc_id to a specific ES document field and pass it to the Document constructor. Currently, it is not passed so it is generated automatically. 
```
Document(text=value, extra_info=hit["_source"], embedding=embedding)
```
When the same document is fetched next time, this auto-generated ID differs so it is impossible to decide if the content is the same or if the Llama index needs to be updated.

**Comment by EmanuelCampos** [comment]
solved on

https://github.com/jerryjliu/llama_index/issues/262#issuecomment-1577037963
