### ISSUE TITLE
BilibiliTranscriptReader not working properly

### ISSUE THREAD

**Issue by pingzhili** [emptycrown/llama-hub#156]
I've tried the given example url and some other urls, they all raise the same warning like this: 

```
UserWarning: No subtitles found for video: https://www.bilibili.com/video/BV1Km4y1z723/. Return Empty transcript.
  warnings.warn(
[Document(text='', doc_id='9ea3b653-2696-468c-8586-045882f39530', embedding=None, doc_hash='dc937b59892604f5a86ac96936cd7ff09e25f18ae6b758e8014a24c7fa039e91', extra_info=None)]
```

Seems that the `bilibili_api` is not working properly? @AlexZhangji

**Comment by AlexZhangji** [comment]
@pingzhili, thank you for bringing this up!

It seems that the video you shared may not have any subtitles or transcripts available. It appears that many recent uploads to the Bilibili no longer include subtitles by default. (previously, they have auto sub option enabled by default)

This code still works for videos that have subtitles. 
For example, using video from the same channel, which has subtitles available:
https://www.bilibili.com/video/BV14P411T79F
![image](https://user-images.githubusercontent.com/3280924/229258013-027466a3-8f57-43d5-868a-1314d84d6350.png)

**Comment by AlexZhangji** [comment]
After further tests, I did find that some videos do have subtitles originally, but for some reason, their transcripts are not displayed. 
Unfortunately, there is no official API available for this, and changes to the official website can sometimes cause issues.


I will investigate this matter further and see if we can find a solution. In the meantime, please feel free to try out other methods or contribute!

**Comment by EmanuelCampos** [comment]
it seems that this issue isn't directly related to llama-hub, closing it for now
