### ISSUE TITLE
SlackReader is not skipping main messages before earliest_date but is skipping messages inside threads

### ISSUE THREAD

**Issue by shikhar-sharma1703** [emptycrown/llama-hub#168]
**Description**
When using the SlackReader with a specified earliest_date, main messages that were posted before the earliest_date are still being returned, but messages inside threads are being skipped correctly. Here's an example of the code I used:
```
earliest_date = datetime(2023, 3, 26)
loader = SlackReader(
    slack_token,
    earliest_date=earliest_date,
)
```
I expected that only messages posted after the earliest_date would be returned, but this is not the case. However, when I added a message to a thread of an older main message (posted on March 22), both the newer thread message and the older main message were returned, as expected.

**Comment by shufanhao** [comment]
@shikhar-sharma1703 how did you setup slack ? what's the meaning of <Slack API Token> ? how to setup it ?

**Comment by EmanuelCampos** [comment]
I ran and appears to be solved, closing due inactivity
