### ISSUE TITLE
Missing URL reference for S3 loader

### ISSUE THREAD

**Issue by gCalixtoS** [emptycrown/llama-hub#176]
Last commit has an issue in the S3 connector, I´m not being able to connect to the S3 bucket. @claudenm Please check line 71 for the loader, I think there should be accesing the attribute s3_endpoint_url and not s3_url... 

 File "/home/vflow/.local/lib/python3.9/site-packages/llama_index/readers/llamahub_modules/s3/base.py", line 71, in load_data
    s3_client = session.client("s3", endpoint_url=self.s3_url)
AttributeError: 'S3Reader' object has no attribute 's3_url'
 'S3Reader' object has no attribute 's3_url' [file '/home/vflow/.local/lib/python3.9/site-packages/llama_index/readers/llamahub_modules/s3/base.py', line 71]

**Comment by gunwant11** [comment]
![image](https://user-images.githubusercontent.com/72063762/231198268-d19cd902-8826-4470-ac04-6e4a1d92ec1a.png)

I went through the code and found that the load data function is referencing s3_url where it should reference s3_endpoint_url as s3_url is not defined in S3Reader

**Comment by EmanuelCampos** [comment]
solved on #187
