### ISSUE TITLE
Notion reader: KeyError 'results'

### ISSUE THREAD

**Issue by BayramAnnakov** [emptycrown/llama-hub#177]
Notion reader doesn't work for me - any ideas?

Created integration token, granted access to the appropriate database

│ /usr/local/lib/python3.9/dist-packages/llama_index/readers/llamahub_modules/notion/base.py:56 in │
│ _read_block                                                                                      │
│                                                                                                  │
│    53 │   │   │   )                                                                              │
│    54 │   │   │   data = res.json()                                                              │
│    55 │   │   │                                                                                  │
│ ❱  56 │   │   │   for result in data["results"]:                                                 │
│    57 │   │   │   │   result_type = result["type"]                                               │
│    58 │   │   │   │   result_obj = result[result_type]                                           │
│    59                                                                                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
KeyError: 'results'

**Comment by BayramAnnakov** [comment]
closing issue, didn't realize that page id should be given without the leading page name, i.e. if your page URL is https://www.notion.so/Getting-Started-fbfddd0fffb3485cac7ca0c80d4b3320 then page id is fbfddd0fffb3485cac7ca0c80d4b3320

**Comment by McManCSU** [comment]
Thanks for this - tripped me up too. Assuming they never change the format, I just used a regexp to get the `md5` from the URL
```python
            page_id = re.findall("([0-9a-f]{32})", link)[0]
```

**Comment by nick-youngblut** [comment]
@BayramAnnakov you should re-open this issue since the code does not handle API requests properly, which results in a `KeyError` instead of raising the API error message (e.g., `Could not find block with ID: XXXXX. Make sure the relevant pages and databases are shared with your integration`)
