### ISSUE TITLE
S3 loader to be supported in AWS Lambda functions

### ISSUE THREAD

**Issue by aladevlearning** [emptycrown/llama-hub#178]
When running below code in a Python Lambda function

```
 S3Reader = download_loader("S3Reader")
    loader = S3Reader(bucket='<BUCKET>', key='<KEY>', aws_access_id='<ACCESS_ID>', aws_access_secret='<ACCESS_SECRET>')
    documents = loader.load_data()
```

There is an issue as lambda function attempt to access in write mode something that is not supposed to.
Would be nice to extend the loader so that either is able to access tmp folder in Lambda or makes it easier to access S3 objects.

OpenBLAS WARNING - could not determine the L2 cache size on this system, assuming 256k
START RequestId: d859d58a-482d-4a34-807a-3a4ff68aff4d Version: $LATEST
[ERROR] OSError: [Errno 30] Read-only file system: '/var/task/llama_index/readers/llamahub_modules/library.json'
Traceback (most recent call last):
  File "/var/task/app.py", line 16, in lambda_handler
    S3Reader = download_loader("S3Reader")

**Comment by EmanuelCampos** [comment]
duplicated of #318

**Comment by EmanuelCampos** [comment]
solved on https://github.com/emptycrown/llama-hub/pull/318
