### ISSUE TITLE
S3 loader InvalidAccessKeyId

### ISSUE THREAD

**Issue by HubertPiotrowski** [emptycrown/llama-hub#189]
When providing the correct Access ID and Access Secret ID, there is a an error:
ClientError: An error occurred (InvalidAccessKeyId) when calling the ListObjects operation: The AWS Access Key Id you provided does not exist in our records.

According to this source:
https://stackoverflow.com/questions/43907689/boto3-error-the-aws-access-key-id-you-provided-does-not-exist-in-our-records

We are missing aws_session_token, but it is not yet available in the code itself for S3 loader

**Comment by EmanuelCampos** [comment]
It should already by fixed. Feel free to open the issue if the problem persists
