### ISSUE TITLE
Jira Reader: TypeError: 'NoneType' object is not subscriptable.

### ISSUE THREAD

**Issue by shikhar-sharma1703** [emptycrown/llama-hub#191]
Code:

```
from llama_index import download_loader
import os

JiraReader = download_loader('JiraReader')
reader = JiraReader(email=EMAIL, api_token=JIRA_TOKEN,
                    server_url=SERVER_URL)

documents = reader.load_data(query='project=first-project')

print(documents)

```
Error:
```
Traceback (most recent call last):
  File "/Users/shikharsharma/Desktop/python-tests/jira/jira-connector.py", line 12, in <module>
    documents = reader.load_data(query='project=first-project')
  File "/Users/shikharsharma/Library/Python/3.9/lib/python/site-packages/llama_index/readers/llamahub_modules/jira/base.py", line 40, in load_data
    if issue.raw['fields']['customfield_10009']['showField']:
TypeError: 'NoneType' object is not subscriptable
```

**Comment by MarkusOdenthal** [comment]
I get the same error. For our Jira Tickets, I need help finding the 'customfield_10009'. Do you know if we need this field? Otherwise, can we get deleted maybe this code part?

**Comment by MarkusOdenthal** [comment]
There is also another issue that we can only get 50 issues per query. Maybe we can also implement code to get all issues for a query. I can do it @emptycrown if you're ok with this?

**Comment by jerryjliu** [comment]
@BearGuy do you happen to know what is causing this?

**Comment by jerryjliu** [comment]
> There is also another issue that we can only get 50 issues per query. Maybe we can also implement code to get all issues for a query. I can do it @emptycrown if you're ok with this?

@MarkusOdenthal would love that as a feature!
