### ISSUE TITLE
ModuleNotFoundError when trying to use Github Repository Loader

### ISSUE THREAD

**Issue by TheSpivack** [emptycrown/llama-hub#209]
I'm attempting to use the Github Repository Loader, but I am unable to get past this error.  Following along the [README for the loader](https://github.com/emptycrown/llama-hub/tree/main/loader_hub/github_repo#readme), I have the following code at the top of my file.

```py
import os

from llama_index import download_loader
download_loader("GithubRepositoryReader")

from llama_index.readers.llamahub_modules.github_repo import GithubRepositoryReader, GithubClient
```

Immediately, the IDE is giving me the error: `Cannot find reference 'GithubRepositoryReader' in 'imported module llama_index.readers.llamahub_modules.github_repo'`

I found I am able to fix the IDE errors my changing the import statement as follows:
```py
from llama_index.readers.llamahub_modules.github_repo.base import GithubRepositoryReader
from llama_index.readers.github_readers.github_api_client import GithubClient
```

However, when I run the script, I am still receiving the same error during runtime.  However, the error is occuring during the call to `download_loader("GithubRepositoryReader")`. So not really sure how to resolve this issue since it's happening before it even gets to any of my code...

**Comment by EmanuelCampos** [comment]
It seems to be solved, closing for now
