### ISSUE TITLE
Data loaders are not available

### ISSUE THREAD

**Issue by mrcabellom** [emptycrown/llama-hub#218]
After this pull request https://github.com/emptycrown/llama-hub/pull/181 a lot of loaders were removed from the library.json file…any reason?

**Comment by mrcabellom** [comment]
@jerryjliu could you take a look at this? A lot of loaders have disappeared from the official web page.

**Comment by jerryjliu** [comment]
@mrcabellom is this still an issue? the ones removed in that one should be fixed now

**Comment by mrcabellom** [comment]
@jerryjliu Some loaders are still missing in the library.json file

**Comment by mrcabellom** [comment]
For example, the azcognitive_search is missing…
