### ISSUE TITLE
SlackReader exceeding rate limit too fast

### ISSUE THREAD

**Issue by BenBatsir** [emptycrown/llama-hub#226]
From my understanding:
`                result_messages.extend(
                    self._read_message(channel_id, message["ts"])
                    for message in conversation_history
                )`
The above section read every message/reply per message history and so rate limit is reached very fast

**Comment by EmanuelCampos** [comment]
duplicated of https://github.com/emptycrown/llama-hub/issues/269

let's move to there since there are already few ideas to solve
