### ISSUE TITLE
pymupdf and llama_index 

### ISSUE THREAD

**Issue by namp** [emptycrown/llama-hub#239]
The example at https://llamahub.ai/l/file-pymu_pdf is broken

Here's my slightly modified code:

```
from pathlib import Path
from llama_index import GPTVectorStoreIndex, download_loader
PyMuPDFReader = download_loader("PyMuPDFReader")
loader = PyMuPDFReader()
documents = loader.load(file=Path('./paper.pdf'), metadata=True)
index = GPTVectorStoreIndex(documents)
index.query('What was the dataset used?')
```

TypeError: PyMuPDFReader.load() got an unexpected keyword argument 'file'

Python 3.10 and latest versions of llama_index and pymupdf

**Comment by mkrupczak3** [comment]
I've found the code needs further modification now. My version is:

```python
    PyMuPDFReader = download_loader("PyMuPDFReader")
    loader = PyMuPDFReader()
    documents = loader.load(file_path=Path('./document.pdf'), metadata=False)

    index = GPTVectorStoreIndex.from_documents(documents)
    query_engine = index.as_query_engine()
    query_engine.query("What is the title of this document?")
```

However, I get the following error, which appears to be a bug with the PyMuPDFReader loader due to it not properly converting input into strings:

```
File "/opt/homebrew/lib/python3.11/site-packages/llama_index/node_parser/node_utils.py", line 49, in get_nodes_from_document
    text_splits = get_text_splits_from_document(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/llama_index/node_parser/node_utils.py", line 29, in get_text_splits_from_document
    text_splits = text_splitter.split_text_with_overlaps(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/llama_index/langchain_helpers/text_splitter.py", line 166, in split_text_with_overlaps
    splits = text.split(self._separator)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: a bytes-like object is required, not 'str'
```
@jerryjliu  @iamarunbrahma

**Comment by EmanuelCampos** [comment]
You should use `file_path` instead of `file` as an argument

```py
from pathlib import Path
from llama_index import download_loader

PyMuPDFReader = download_loader("PyMuPDFReader")

loader = PyMuPDFReader()
documents = loader.load(file_path=Path('./article.pdf'), metadata=True)

```

**Comment by EmanuelCampos** [comment]
> I've found the code needs further modification now. My version is:
> 
> ```python
>     PyMuPDFReader = download_loader("PyMuPDFReader")
>     loader = PyMuPDFReader()
>     documents = loader.load(file_path=Path('./document.pdf'), metadata=False)
> 
>     index = GPTVectorStoreIndex.from_documents(documents)
>     query_engine = index.as_query_engine()
>     query_engine.query("What is the title of this document?")
> ```
> 
> However, I get the following error, which appears to be a bug with the PyMuPDFReader loader due to it not properly converting input into strings:
> 
> ```
> File "/opt/homebrew/lib/python3.11/site-packages/llama_index/node_parser/node_utils.py", line 49, in get_nodes_from_document
>     text_splits = get_text_splits_from_document(
>                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/homebrew/lib/python3.11/site-packages/llama_index/node_parser/node_utils.py", line 29, in get_text_splits_from_document
>     text_splits = text_splitter.split_text_with_overlaps(
>                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/homebrew/lib/python3.11/site-packages/llama_index/langchain_helpers/text_splitter.py", line 166, in split_text_with_overlaps
>     splits = text.split(self._separator)
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
> TypeError: a bytes-like object is required, not 'str'
> ```
> 
> @jerryjliu @iamarunbrahma

Feel free to open a new issue to discuss this. If you've already found a solution, feel free to open a PR!
