### ISSUE TITLE
Some items retrieved from confluence space do not have a 'body'

### ISSUE THREAD

**Issue by aerickson-clt** [emptycrown/llama-hub#254]
https://github.com/emptycrown/llama-hub/blob/1fe452119cfc04ad2f6f43aa3ccffbe81b389f50/loader_hub/confluence/base.py#LL136C1-L137C1

From my code I called
`nodes = reader.load_data(space_key=space_key, include_attachments=False, include_children=False, limit=3)`

Which causes loader_hub/confluence/base.py to call the line `pages_iter = self.confluence.get_all_pages_from_space(space_key, start=start, limit=limit)` from the atlassian-python-api documented at https://atlassian-python-api.readthedocs.io/confluence.html

Each of these pages is processed by extracting the 'body' at line 136 with `text = text_maker.handle(page['body']['storage']['value']) + "".join(attachment_texts)`

The following error occurs.

```
Traceback (most recent call last):
  File "path/to/index_confluence.py", line 82, in <module>
    nodes = reader.load_data(space_key=space_key, include_attachments=False, include_children=False, limit=3)
  File "path/to/llama_index/readers/llamahub_modules/confluence/base.py", line 89, in load_data
    doc = self.process_page(page, include_attachments, text_maker)
  File "path/to/llama_index/readers/llamahub_modules/confluence/base.py", line 136, in process_page
    text = text_maker.handle(page['body']['storage']['value']) + "".join(attachment_texts)
KeyError: 'body'
```

**Comment by aerickson-clt** [comment]
Looks like the issue is at line 76, which is missing the parameter `expand='body.storage.value'`

```
                pages_iter = self.confluence.get_all_pages_from_space(space_key, start=start, limit=limit)
```

**Comment by aqpatel** [comment]
Great work with the confluence loader. 
Suggestion: Instead of hardcoding the `expand` value, allow an expand parameter to passed as input. It would allow fetching the document in a different format like `editor`, `export_view` etc to accurately convert the content to `md` format.
If its okay, I can make changes and contribute by raising a PR. Cheers!
