### ISSUE TITLE
Feature request: provide a PyPI package

### ISSUE THREAD

**Issue by krokicki** [emptycrown/llama-hub#260]
Although I appreciate the allure of getting loader code quickly and easily, I think the `download_loader` method of library distribution is problematic for many reasons:
* It violates the principle of least astonishment. 
* It creates unnecessary runtime complexity and latency. 
* Makes it difficult to version dependencies. 
* Cannot be used in a secure environment because it increases the possibility for supply chain attacks.
* Makes LlamaHub more difficult to use inside containers because it requires writeable disk cache. 

It also looks like `download_loader` is already causing many issues, reported here (#81, #150, #209, etc.) and on Discord.

Perhaps I'm missing something, but the entire llama-hub code base is 1.6 MB so it seems that there's no reason it couldn't be built, versioned, and distributed using a well-understood mechanism like PyPI.

**Comment by logan-markewich** [comment]
This happened today actually!

**Comment by logan-markewich** [comment]
https://twitter.com/llama_index/status/1663703770893783040?s=20

**Comment by krokicki** [comment]
Awesome! Huge props to the @jerryjliu for moving so fast. I will go ahead and close this.

**Comment by jerryjliu** [comment]
yeah @krokicki tahnsk for flagging this, this issue was one of the motivations for creating the llama-hub package :)
