### ISSUE TITLE
Where do tests go for loaders?

### ISSUE THREAD

**Issue by bd-cp** [emptycrown/llama-hub#265]
I considered extending some of the loaders, but no tests exist. Since there are so many loaders and no (loader) tests it seems like a pattern or policy. Can I add tests to the main test folder? Should they go into the loader's folder? Is it considered a bad style to add tests for some reason?

(I am new to the repo; apologies if this question has an answer elsewhere already. Please point to it in that case.)

**Comment by EmanuelCampos** [comment]
There's a tests folder 

https://github.com/emptycrown/llama-hub/tree/main/tests
