### ISSUE TITLE
SlackReader sleep time doesn't work, getting rate limited

### ISSUE THREAD

**Issue by brainstencil** [emptycrown/llama-hub#269]
I get rate limited by the Slack API when using SlackReader.

I think SlackReader is supposed to sleep for a suggested time, defined in the variable: retry_after which is supposed to be intercepted from the header of the Slack API error message. It seems to always be 10 seconds and is never enough to avoid rate limiting. 

I created a default wait time of 15 seconds, and added 10 seconds for each consecutive error and that seems to avoid getting rate limited.

**Comment by shufanhao** [comment]
@brainstencil how did you setup slack ? what's the meaning of `<Slack API Token>`  ? how to setup it ?

**Comment by EmanuelCampos** [comment]
It seems to be solved, feel free to open a PR with this improvement

@shufanhao if needed open a new issue with your question, we will be happy to help
