### ISSUE TITLE
GithubReader import error

### ISSUE THREAD

**Issue by abra1l** [emptycrown/llama-hub#278]
After recent changes on GithubRepositoryReader  
`|   File "/app/redacted/retrievers/github.py", line 8, in <module>  

|     download_loader("GithubRepositoryReader")

|   File "/usr/local/lib/python3.11/site-packages/llama_index/readers/download.py", line 211, in download_loader

|     spec.loader.exec_module(module)  # type: ignore

|     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

|   File "/usr/local/lib/python3.11/site-packages/llama_index/readers/llamahub_modules/github_repo/base.py", line 20, in <module>

|     from llama_index.readers.file.base import DEFAULT_FILE_READER_CLS  

| ImportError: cannot import name 'DEFAULT_FILE_READER_CLS' from 'llama_index.readers.file.base'  (/usr/local/lib/python3.11/site-packages/llama_index/readers/file/base.py)`

**Comment by EmanuelCampos** [comment]
It seems to be solved, closing for now per inactivity
