### ISSUE TITLE
PubmedReader

### ISSUE THREAD

**Issue by DrSebastianK** [emptycrown/llama-hub#294]
Hello! I started using the PubmedReader, but I'm experiencing some problems. It seems that the papers, which are returned have nothing to do with my search query. I type for example 'temporomandibular disorders' as the query and get results which have nothing to do with the particular disease. Anyone experienced something similar? Does the search query need some further specifications?

**Comment by EmanuelCampos** [comment]
It runs here, but the returned results mentioned only "temporomandibular", not fully "temporomandibular disorders"

You can explore Pubmed parameters and open a PR if find a better way to achieve that, it will be very welcome!

parameters available on pubmed: https://www.ncbi.nlm.nih.gov/books/NBK25499/
