### ISSUE TITLE
How to split text for the best effect

### ISSUE THREAD

**Issue by jespon** [emptycrown/llama-hub#340]
I have a lot of documents,Using GPTVectorStoreIndex.from_documents default for indexing documents is a chunk with a length of 1024 tokens, which can result in incomplete answers to questions

The answer to a certain question in the document is relatively long. Increase chunk_size I don't think it can solve this problem very well，How to ensure the completeness of the answer in blocks?

**Comment by tutu-sol** [comment]
I believe 'llama_index' repo is a better place to ask this question?

Anyway, can you give more details about you usage so others can give better suggestions?
For example. Does the answer require a context covering more than 1024 tokens? Does the necessary context cross the chunk boundaries?

**Comment by EmanuelCampos** [comment]
As mentioned above you can open this issue on https://github.com/jerryjliu/llama_index

you can get answers fast from the core contributors
