### ISSUE TITLE
KnowledgeBaseWebReader Playwright error

### ISSUE THREAD

**Issue by kbillesk** [emptycrown/llama-hub#342]
Using the KnowledgeBaseWebReader produces a Playwright-related error. The following code:

`from llama_hub.web.knowledge_base.base import KnowledgeBaseWebReader

loader = KnowledgeBaseWebReader(root_url='https://www.datatilsynet.dk', 
link_selectors=['.afgoerelser'],
article_path='/afgoerelser/afgoerelser/',
body_selector='.rich-text',
title_selector='.heading')
documentsweb = loader.load_data()`
Produces this:
File ~/anaconda3/envs/spyder-env/lib/python3.9/site-packages/playwright/sync_api/_context_manager.py:48 in __enter__
    raise Error(
Error: It looks like you are using Playwright Sync API inside the asyncio loop.
Please use the Async API instead.

**Comment by EmanuelCampos** [comment]
KnowledgeBaseWebReader uses playwright sync behind the hood, so this error happens if you're calling it inside of an async loop, removing asyncio or doing some adjustments on llamahub to use playwright async API will solve your problem
