### ISSUE TITLE
WordPress Loader - authentication not used for GET request

### ISSUE THREAD

**Issue by alexbluephoenix** [emptycrown/llama-hub#359]
I was trying to use Wordpress Loader (with simple code provided in the hub) .
I did receive Anthentication message error, for non authenticated user despite the fact that I was using following syntax
```python
loader = WordpressReader(url="https://www.mysite.com", username="my_username", password="my_password")
```
I had to update the call to requests.get to pass user/ name (this is in the get_posts_page definition)
```python
def get_posts_page(self, current_page: int = 1):
        import requests

        url = f"{self.url}/wp-json/wp/v2/posts?per_page=100&page={current_page}"
        response = requests.get(url,auth=(self.username,self.password))
````
the auth= () part was missing. I did struggle a bit to figure it out but after this small modificatiion it was working fine

**Comment by EmanuelCampos** [comment]
It seems to be solved, closing for now
