### ISSUE TITLE
WordPress Loader - __init__() takes exactly 1 positional argument (2 given) errror when building document

### ISSUE THREAD

**Issue by alexbluephoenix** [emptycrown/llama-hub#360]
Trying to use the WordPress loader to get all data from a website using following basic code
```python
from llama_index import download_loader
WordpressReader = download_loader("WordpressReader")
loader = WordpressReader(url="myURL", username="xxx", password="xxxxx")
documents = loader.load_data()
```
Data is correctly extracted from WP, but receiving the following error when enterring the loop to build the Documents
```python
File [~/LLM_Projects/readanything/.venv/lib/python3.10/site-packages/llama_index/readers/llamahub_modules/wordpress/base.py:58](https://file+.vscode-resource.vscode-cdn.net/Users/alexisdesaintjean/LLM_Projects/readanything/~/LLM_Projects/readanything/.venv/lib/python3.10/site-packages/llama_index/readers/llamahub_modules/wordpress/base.py:58), in WordpressReader.load_data(self)

     57     results.append(
---> 58         Document(
     59             body,
     60             extra_info=extra_info,
     61         )
     62     )
     64 return results

File [~/LLM_Projects/readanything/.venv/lib/python3.10/site-packages/pydantic/main.py:332](https://file+.vscode-resource.vscode-cdn.net/Users/alexisdesaintjean/LLM_Projects/readanything/~/LLM_Projects/readanything/.venv/lib/python3.10/site-packages/pydantic/main.py:332), in pydantic.main.BaseModel.__init__()

TypeError: __init__() takes exactly 1 positional argument (2 given)
```
I was not able to figure out what is going wrong in the pydantic init

**Comment by judetsg** [comment]
I have exactly the same error when using the EpubReader. I would also be very interested in what is going wrong.
I suspect this has something to do with the latest version of llama-index (0.7.2). 
A few days ago, I was able to run my code without any problem with a lower version of llama-index.
Some breaking change probably.

**Comment by AlessandroAnnini** [comment]
I have the same error using PptxReader

```
- llama-index==0.7.12
```

**Comment by biosugar0** [comment]
The same error also occurs in ZendeskReader.
```
    docs = loader.load_langchain_documents()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/llama_index/readers/base.py", line 19, in load_langchain_documents
    docs = self.load_data(**load_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/llama_index/readers/llamahub_modules/zendesk/base.py", line 47, in load_data
    Document(
  File "pydantic/main.py", line 332, in pydantic.main.BaseModel.__init__
TypeError: __init__() takes exactly 1 positional argument (2 given)
```

llama-index==0.8.0

**Comment by logan-markewich** [comment]
@alexbluephoenix Just opened a PR to fix this

Everyone else (@judetsg @AlessandroAnnini @biosugar0 ) You seem to be using outdated versions of llama-hub. The errors and lines of code referenced don't line up with the current source code for those readers. This error happens because the `Document` object changed to a pydantic object, which requires all attributes to be kwargs. This has been largely fixed in llama-hub (minus the Wordpress loader, just opened a PR).

If you are using download loader, you can refresh the cache `download_loader(..., refresh_cache=True)`

Otherwise, you can install llama-hub with `pip install llama-hub` and import the package directly.

**Comment by biosugar0** [comment]
@logan-markewich, thank you for your helpful suggestion!

By using the `refresh_cache=True` parameter, we've managed to successfully resolve the issue. 

```
ZendeskReader = download_loader("ZendeskReader", refresh_cache=True)
```

**Comment by EmanuelCampos** [comment]
It seems to be solved, closing for now
