### ISSUE TITLE
HubspotReader

### ISSUE THREAD

**Issue by kasiahewelt** [emptycrown/llama-hub#373]
Hello,

I am trying to use HubSpot Loader from: https://llama-hub-ui.vercel.app/l/hubspot
I already created a private app and added API key to provided code, but facing an error:

urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.hubapi.com', port=443): Max retries exceeded with url: /crm/v3/objects/deals?limit=100 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1002)')))

I am using python 3.11

**Comment by logan-markewich** [comment]
Are you using a VPN or maybe a work laptop? This is pretty common for those cases

Try running the code in colab maybe

**Comment by kasiahewelt** [comment]
this solved the problem:
https://stackoverflow.com/questions/52805115/certificate-verify-failed-unable-to-get-local-issuer-certificate
