### ISSUE TITLE
Can't load .ppt files with the Pptx file loader

### ISSUE THREAD

**Issue by niels-bosman** [emptycrown/llama-hub#374]
I just tried to use the PptxLoader to load my older PowerPoint file and I got the following error:

```bash
pptx.exc.PackageNotFoundError: Package not found at 'documents/ProductMarketAnalysis_1.ppt'
```

Is this something that is supposed to happen or should this loader support `.ppt` too? I already tried manually renaming the file extension to .pptx but no luck there.

**Comment by tutu-sol** [comment]
The loader does not work for ppt files (this is the limitation of the underlying python library used)

Moreover, parsing a ppt file is very difficult in general, as the old format is designed for rendering on screen.

I think it would be better if you can convert the ppt file into pptx.

**Comment by EmanuelCampos** [comment]
Closing for now due inactivity
