### ISSUE TITLE
Llama Hub website connectors all say 5 months ago

### ISSUE THREAD

**Issue by kevinlu1248** [emptycrown/llama-hub#402]
![Screenshot_20230718_150058-1](https://github.com/emptycrown/llama-hub/assets/26889185/32d15d13-197d-4f84-9ef6-3f54477f2572)

It could potentially be hard-coded somewhere. Is the frontend also open-source? If so, we can install Sweep (https://github.com/sweepai/sweep#-getting-started) on it to fix this.

**Comment by EmanuelCampos** [comment]
Closing for now, sounds to be fixed but I didn't find the PR yet
