### ISSUE TITLE
wikipedia tool missing import

### ISSUE THREAD

**Issue by krypterro** [emptycrown/llama-hub#403]
base.py appears to be missing import wikipedia, line 47 calls wikipedia but it's not been imported, adding import wikipedia fixes the error

**Comment by tyre** [comment]
Which version are you using? In `main`, `import wikipedia` is on line 24:

https://github.com/emptycrown/llama-hub/blob/main/llama_hub/wikipedia/base.py#L24

**Comment by EmanuelCampos** [comment]
Closing for now due inactivity
