### ISSUE TITLE
vector_index

### ISSUE THREAD

**Issue by simrankaurjolly16** [emptycrown/llama-hub#408]
list_index = GPTListIndex(nodes, storage_context=storage_context)
keyword_table_index = GPTSimpleKeywordTableIndex(nodes, storage_context=storage_context)
--> These two are working fine
vector_index = GPTVectorStoreIndex(nodes, storage_context=storage_context)
--> This is returning an error response as "AuthenticationError".
AuthenticationError: No API key provided. You can set your API key in code using 'openai.api_key = <API-KEY>', or you can set the environment variable OPENAI_API_KEY=<API-KEY>). If your API key is stored in a file, you can point the openai module at it with 'openai.api_key_path = <PATH>'. You can generate API keys in the OpenAI web interface. See https://platform.openai.com/account/api-keys for details.
OPENAI_API_KEY is properly configured in .env file & "GPTListIndex" and "GPTSimpleKeywordTableIndex" are working fine without any issues. Do we know why "GPTVectorStoreIndex" is returning "AuthenticationError" ?

**Comment by simrankaurjolly16** [comment]
vector_index = GPTVectorStoreIndex(nodes, storage_context=storage_context)

**Comment by logan-markewich** [comment]
Vector store index requires embeddings at index construction, the others don't.

If you are working in a notebook, I've noticed you have to set the key on the module as well

```
import openai
openai.api_key = ".."
```
