### ISSUE TITLE
Data loader and seismic 

### ISSUE THREAD

**Issue by lewis-ljh** [emptycrown/llama-hub#417]
Hi, Im currently building a support chat box using LLM and currently just creating my embeddings. Im trying to make embeddings from a platform called Seismic. What data loader from llama_hub would be recommended for this? Any tips or recommendations would be appreciated!

**Comment by EmanuelCampos** [comment]
Not sure if I understood your question.

Currently, the embeddings are generated on the [llama_index](https://github.com/jerryjliu/llama_index) side

And you need to choose a loader based on your specific needs, and from which source of knowledge you want to extract the data.
