### ISSUE TITLE
Confluence connector reading pagination

### ISSUE THREAD

**Issue by v2br** [emptycrown/llama-hub#419]
How do you read a huge number of documents from a confluence space? 
Seems like the current implementation is limited by max_num_results only. I don't see a way to do pagination.

**Comment by luke3butler** [comment]
I'm looking at implementing this loader, and checked the code.

According to [this line](https://github.com/emptycrown/llama-hub/blob/35714acbc39373d95a13e4317fd393c6af747662/llama_hub/confluence/base.py#L217) (and every other `if max_num_results is not None:` line in that file), it looks like it'll load all the pages as long as `max_num_results` is omitted or set to `None`.

I'll try to remember to report back if/when I get around to using it.

**Comment by EmanuelCampos** [comment]
Currently, it works as the explanation above, to have a pagination with skip and limit we would need to check on the Confluence API and adapt the implementation, closing this issue for now, feel free to contribute with us
