### ISSUE TITLE
How to use multiple documents in one loader?

### ISSUE THREAD

**Issue by stevevaius2015** [emptycrown/llama-hub#45]
I would like to load multiple document in docx format to index. Is it possible to load and save the resulting index to not run again?

**Comment by emptycrown** [comment]
If you want to load multiple .docx files, you have 2 options:

1. Feed each one into a `DocxReader` and concatentae the resulting documents together.
2. Put them all into a directory and load them with `SimpleDirectoryReader`.

Once you have your final list of documents, create an index with `index = GPTSimpleVectorIndex(documents)`. Then, if you want to save/load it from disk,
```python
# save to disk
index.save_to_disk('index.json')
# load from disk
index = GPTSimpleVectorIndex.load_from_disk('index.json')
```
