### ISSUE TITLE
ERROR:custom_loader:An error occurred while loading data from fileids meta: __init__() takes exactly 1 positional argument (2 given)

### ISSUE THREAD

**Issue by karan00713** [emptycrown/llama-hub#454]
when I tried to load the googledrivereader using 

from llama_index import download_loader
GoogleDriveReader = download_loader("GoogleDriveReader")
loader = GoogleDriveReader()
documents = loader.load_data(folder_id="xxxxxxxxxxxxxxxxxx") it showed error ERROR:custom_loader:An error occurred while loading data from fileids meta: __init__() takes exactly 1 positional argument (2 given), can anyone help what i did wrong?

i'm using llama_index==0.7.14

**Comment by EmanuelCampos** [comment]
duplicated from https://github.com/emptycrown/llama-hub/issues/360#issuecomment-1675662545

take a look there, there's a few solutions
