### ISSUE TITLE
PDFReader how to specify chunk size ?

### ISSUE THREAD

**Issue by xrtechspot** [emptycrown/llama-hub#494]
Here is a way to specify in loader chunk size tu use?

PDFReader = download_loader("PDFReader")
loader = PDFReader()
chunks = loader.load_data(file=Path(file_path))

Thank you

**Comment by EmanuelCampos** [comment]
There's no way to use chunk size on loaders currently, and not sure if it should happen here

You can update the node chunk_size on the llama_index size if needed

https://gpt-index.readthedocs.io/en/latest/end_to_end_tutorials/question_and_answer/terms_definitions_tutorial.html
