### ISSUE TITLE
llama.github_repo: RuntimeError: This event loop is already running in python

### ISSUE THREAD

**Issue by simoneVU** [emptycrown/llama-hub#510]
When trying the code at [llama_hub/github_rep](https://github.com/emptycrown/llama-hub/tree/03cf2fc1c9e2e2073a6af2d21d8d97fb2f14374b/llama_hub/github_repo) on Google Collab, I get the error `RuntimeError: This event loop is already running`.

I fixed it by including this
```
import nest_asyncio
nest_asyncio.apply()
```
before my code, however, my guess is that there is some sort of problem in the source code. This issues is a copy to  #315, I am just wondering whether there is a change to make in the code itself.

Thanks in advance.

**Comment by nsthorat** [comment]
I also have this issue.

**Comment by logan-markewich** [comment]
There's no problem in the source code. Notebooks run in an async loop already, so any other code that uses async needs to be enabled using nest_asyncio

@nsthorat just use the code snippet above, it'll be fine 👍
