### ISSUE TITLE
[Bug]: AttributeError: 'GoogleDriveReader' object has no attribute 'service_account_path'

### ISSUE THREAD

**Issue by rockodragon** [emptycrown/llama-hub#536]
### Bug Description

Unable to connect to google drive. Followed instructions on the Loader page.
https://llamahub.ai/l/google_drive

### Version

0.8.31

### Steps to Reproduce

Followed instructions on the Loader page.
Enabled API
Created Client Auth credentials.
Made files available in same directory
Ran llama index, it downloaded the Loader successfully, and had the correct Google Folder ID, received this error.

  File ".pyenv/versions/3.10.13/lib/python3.10/site-packages/llama_index/readers/llamahub_modules/google_drive/base.py", line 368, in load_data
    self._creds, self._drive = self._get_credentials()
  File ".pyenv/versions/3.10.13/lib/python3.10/site-packages/llama_index/readers/llamahub_modules/google_drive/base.py", line 75, in _get_credentials
    elif os.path.exists(self.service_account_path):
AttributeError: 'GoogleDriveReader' object has no attribute 'service_account_path'

**Comment by emmawestbrook** [comment]
I fixed this issue with specifically passing it the parameter:
`loader.service_account_path = "./llmapi/llamaindex/credentials.json"`
and then loaded documents in after that.

**Comment by rockodragon** [comment]
> I fixed this issue with specifically passing it the parameter:
> `loader.service_account_path = "../credentials.json"` or whatever your relative file path is.
> And then loaded documents in after that. However, I'm running into other problems with this loader, so this still may not get it working for you.

Thanks @emmawestbrook 
Yes, that helped it find the file, but now it's complaining the file is missing fields. 
"google.auth.exceptions.MalformedError: Service account info was not in the expected format, missing fields client_email, token_uri."

oddly "token_uri" is in there, but "client_email" is not.

**Comment by EmanuelCampos** [comment]
solved on https://github.com/emptycrown/llama-hub/pull/567
