### ISSUE TITLE
[Documentation]: better example link for Wikipedia Loader

### ISSUE THREAD

**Issue by jamesbraza** [emptycrown/llama-hub#549]
### Documentation Issue Description

The Wikipedia Loader page provides an examples link that just points to https://github.com/emptycrown/llama-hub/tree/main.  I don't see any examples provided here for it.

What would be a better link for Wikipedia examples?

### Documenation Link

https://llamahub.ai/l/wikipedia

**Comment by EmanuelCampos** [comment]
https://gpt-index.readthedocs.io/en/stable/examples/index_structs/knowledge_graph/KnowledgeGraphIndex_vs_VectorStoreIndex_vs_CustomIndex_combined.html#load-data-from-wikipedia

That's an example, but doesn't have any other one here on llama-hub.

Feel free to open a PR!
