### ISSUE TITLE
Loader Issue

### ISSUE THREAD

**Issue by pruthvishetty** [emptycrown/llama-hub#81]
I'm trying to follow the steps in `https://llamahub.ai/l/file-unstructured and while running SimpleDirectoryReader = download_loader("SimpleDirectoryReader")`, I get the following error `No such file or directory: '/Users/some_username/opt/anaconda3/lib/python3.9/site-packages/llama_index/readers/llamahub_modules/file/base.py'`  Any  ideas what I'm doing wrong and suggestions to fix it? Thank you in advance!

**Comment by pruthvishetty** [comment]
I'm able to use `from llama_index import SimpleDirectoryReader` so that's fixed, but following https://llamahub.ai/l/file-unstructured, when I run `documents = loader.load_data()` I get the following error: `'str' object has no attribute 'parser_config_set'` Any pointers? TIA!

**Comment by EmanuelCampos** [comment]
Appears to be fixed, closing for now
