### ISSUE TITLE
SimpleDirectoryReader issue

### ISSUE THREAD

**Issue by pruthvishetty** [emptycrown/llama-hub#85]
In addition to #81, Importing the `SimpleDirectoryReader` from `llama_index` and then trying to parse certain files throughout a directory as shown in [this page](https://llamahub.ai/l/file-unstructured) gives the following error: `'str' object has no attribute 'parser_config_set'`. Any ideas? TIA!

**Comment by EmanuelCampos** [comment]
Appears to be fixed, closing for now as well
